github_runner_personal_access_token: insert your token here
github_runner_name: name your runner
github_runner_repo: user-name/repo

github_runner_labels: self-hosted

github_runner_org: false
github_runner_org_name: org name

github_runner_java: false
github_runner_java_mount_usb: false
github_runner_android: false
github_runner_android_expose_adb_ports: false
github_runner_java_image: compscidr/github-runner-android:latest
github_runner_non_java_image: myoung34/github-runner:latest

github_runner_env_file: false
github_runner_env_filename: ".env"

github_runner_adb_port: 5037

github_runner_github_host: "github.com"
